spring:
  datasource:
    url: jdbc:postgresql://ep-steep-glade-ao3pmkp7.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_dF3uObEpfUD4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
    secret: 3DU4i604p9m9qOWZQjWeF6vRR1hRBUQlniSQRgvcpYo=

frontend:
    url: http://localhost:5173